[toolchain]
solana_version = "1.16.25"

[programs.localnet]
quadratic_market = { idl = "target/idl/quadratic_market.json", address = "FPaJasqbU2qULcJpbiGwduJix6dFRGK8JUefbXbSDcrN" }

[programs.devnet]
quadratic_market = { idl = "target/idl/quadratic_market.json", address = "FPaJasqbU2qULcJpbiGwduJix6dFRGK8JUefbXbSDcrN" }

[programs.mainnet]
quadratic_market = { idl = "target/idl/quadratic_market.json", address = "FPaJasqbU2qULcJpbiGwduJix6dFRGK8JUefbXbSDcrN" }

[provider]
cluster = "devnet"
wallet = "_keys/deploy-wallet.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
deploy = "npx ts-node --transpile-only migrations/deploy.ts"
