[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
quadratic_market = "A1Qgmdwq5XuKbJFpSub2Pf7zrRVNf624nppVTd66Qvxz"

[provider]
cluster = "devnet"
wallet = "/tmp/devnet_wallet.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""

[hooks]
