// quadratic_market Anchor IDL
// Odds stored as basis points: 10000 = 1.0×, 20000 = 2.0×
export const IDL = {
  version: "0.1.0",
  name: "quadratic_market",
  instructions: [
    {
      name: "placeSlipAwait",
      accounts: [
        { name: "globalConfig", isMut: true, isSigner: false },
        { name: "slip", isMut: true, isSigner: false },
        { name: "treasury", isMut: false, isSigner: false },
        { name: "ownerBaseAta", isMut: true, isSigner: false },
        { name: "treasuryBaseAta", isMut: true, isSigner: false },
        { name: "baseMint", isMut: false, isSigner: false },
        { name: "owner", isMut: true, isSigner: true },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "associatedTokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "legs", type: { vec: { defined: "SlipLeg" } } },
        { name: "stake", type: "u64" },
        { name: "cancelDeadline", type: "i64" },
      ],
    },
    {
      name: "resolveSlip",
      accounts: [
        { name: "globalConfig", isMut: true, isSigner: false },
        { name: "slip", isMut: true, isSigner: false },
        { name: "treasury", isMut: false, isSigner: false },
        { name: "owner", isMut: false, isSigner: false },
        { name: "claimerBaseAta", isMut: true, isSigner: false },
        { name: "treasuryBaseAta", isMut: true, isSigner: false },
        { name: "baseMint", isMut: false, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "associatedTokenProgram", isMut: false, isSigner: false },
      ],
      args: [{ name: "slipId", type: "u64" }],
    },
    {
      name: "cancelSlip",
      accounts: [
        { name: "globalConfig", isMut: true, isSigner: false },
        { name: "slip", isMut: true, isSigner: false },
        { name: "treasury", isMut: false, isSigner: false },
        { name: "owner", isMut: false, isSigner: false },
        { name: "cancellerBaseAta", isMut: true, isSigner: false },
        { name: "treasuryBaseAta", isMut: true, isSigner: false },
        { name: "baseMint", isMut: false, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "associatedTokenProgram", isMut: false, isSigner: false },
      ],
      args: [{ name: "slipId", type: "u64" }],
    },
  ],
  accounts: [
    {
      name: "Slip",
      type: {
        kind: "struct",
        fields: [
          { name: "owner", type: "publicKey" },
          { name: "slipId", type: "u64" },
          { name: "epochId", type: "u64" },
          { name: "numLegs", type: "u8" },
          { name: "legMarketIds", type: { array: ["u64", 5] } },
          { name: "legOutcomeIds", type: { array: ["u8", 5] } },
          { name: "legsBoughtMask", type: "u16" },
          { name: "legsSettledMask", type: "u16" },
          { name: "legsWonMask", type: "u16" },
          { name: "totalStake", type: "u64" },
          { name: "totalCost", type: "u64" },
          { name: "potentialPayout", type: "u64" },
          { name: "lockedAmount", type: "u64" },
          { name: "status", type: { defined: "SlipStatus" } },
          { name: "createdAt", type: "i64" },
          { name: "cancelDeadline", type: "i64" },
          { name: "claimed", type: "bool" },
          { name: "bump", type: "u8" },
        ],
      },
    },
    {
      name: "GlobalConfig",
      type: {
        kind: "struct",
        fields: [
          { name: "admin", type: "publicKey" },
          { name: "paused", type: "bool" },
          { name: "oraclePubkey", type: { array: ["u8", 32] } },
          { name: "maxMarketExposure", type: "u64" },
          { name: "lockedPayouts", type: "u64" },
          { name: "totalLpSupply", type: "u64" },
          { name: "lpMint", type: "publicKey" },
          { name: "baseMint", type: "publicKey" },
          { name: "treasury", type: "publicKey" },
          { name: "treasuryBump", type: "u8" },
          { name: "nextMarketId", type: "u64" },
          { name: "challengeWindowSeconds", type: "i64" },
          { name: "settlementDeadlineSeconds", type: "i64" },
          { name: "minFirstLiquidity", type: "u64" },
          { name: "nextSlipId", type: "u64" },
          { name: "currentEpoch", type: "u64" },
          { name: "epochDurationSeconds", type: "i64" },
          { name: "withdrawalCooldownSeconds", type: "i64" },
          { name: "maxSingleBet", type: "u64" },
          { name: "minOddsBps", type: "u64" },
          { name: "maxOddsBps", type: "u64" },
          { name: "houseFeeBps", type: "u64" },
          { name: "operators", type: { array: ["publicKey", 8] } },
          { name: "numOperators", type: "u8" },
          { name: "bump", type: "u8" },
          { name: "nextOrderId", type: "u64" },
          { name: "orderCollateralLocked", type: "u64" },
          { name: "epochPaused", type: "bool" },
          { name: "nextEpochStart", type: "i64" },
        ],
      },
    },
    {
      name: "Market",
      type: {
        kind: "struct",
        fields: [
          { name: "marketId", type: "u64" },
          { name: "creator", type: "publicKey" },
          { name: "startTime", type: "i64" },
          { name: "status", type: { defined: "MarketStatus" } },
          { name: "numOutcomes", type: "u8" },
          { name: "odds", type: { array: ["u64", 8] } },
          { name: "exposure", type: "u64" },
          { name: "settlementTime", type: "i64" },
          { name: "winningOutcome", type: "u8" },
          { name: "outcomeMints", type: { array: ["publicKey", 8] } },
          { name: "title", type: "string" },
          { name: "description", type: "string" },
          { name: "marketType", type: { defined: "MarketType" } },
          { name: "category", type: "u8" },
          { name: "bump", type: "u8" },
          { name: "groupId", type: { option: "u64" } },
          { name: "epochId", type: "u64" },
          { name: "settledInEpoch", type: "bool" },
          { name: "txlineFixtureId", type: { option: "u64" } },
          { name: "txlineProofVerified", type: "bool" },
        ],
      },
    },
  ],
  types: [
    {
      name: "SlipLeg",
      type: {
        kind: "struct",
        fields: [
          { name: "marketId", type: "u64" },
          { name: "outcomeId", type: "u8" },
          { name: "numShares", type: "u64" },
        ],
      },
    },
    {
      name: "SlipStatus",
      type: {
        kind: "enum",
        variants: [
          { name: "Pending" },
          { name: "Active" },
          { name: "Won" },
          { name: "Lost" },
          { name: "Cancelled" },
        ],
      },
    },
    {
      name: "MarketStatus",
      type: {
        kind: "enum",
        variants: [
          { name: "Open" },
          { name: "Suspended" },
          { name: "AwaitingResult" },
          { name: "Proposed" },
          { name: "Settled" },
          { name: "Voided" },
        ],
      },
    },
    {
      name: "MarketType",
      type: {
        kind: "enum",
        variants: [
          { name: "OneXTwo" },
          { name: "OverUnder" },
          { name: "GoalNoGoal" },
        ],
      },
    },
  ],
  errors: [],
} as const;

export type QuadraticMarketIDL = typeof IDL;
